version: '2'
services:
  flaskapp:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/usr/src/daily
    depends_on:
      - database
  database:
    image: postgres:9
    
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ruben
      POSTGRES_PASSWORD: 
      POSTGRES_DB: ruben
      PGDATA: /tmp


      